// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbcvxntommivvndxqemz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiY3Z4bnRvbW1pdnZuZHhxZW16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MTgxNjgsImV4cCI6MjA2NDE5NDE2OH0.-PGlQ9dBjQJ-X1pX62rghrhiK6P_Hki8KYg5bSfUDmc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);